### ISSUE TITLE
"high level" bug-out

### ISSUE THREAD

**Issue by wbarbee** [wbarbee/bin_app#16]
@bigtone1284 @WilliamfShaw 

I'm having a high-level issue as i get deeper into this. 

For the following user story:

"As a user, I would like to save an album (album's info) into my record bin collection."

Again, the album info is coming from a package-based API that is being updated daily, along with the website. Thanks to Tony's help, I can access this data in my browser and have the routes set up so that JSON data is returned to me upon making a search through the url "http://localhost:3000/albums?albums=..."  

The issue that's getting to me in getting the queried data into my database is, will i completely bypass the "albums" table that i currently have and just save, through the client-side, that data into a user's "record bin" collection?  

I currently have a Backbone view that has the following function:

  ```getReviews: function() {
  var albumSearch =
    $('#album-search').val();

  $.ajax({
    url: '/albums?album=' + albumSearch,
    method: 'GET'
  })
  .done(function(reviews) {
    for(var i = 0, i < reviews.length, i++) {
      var url = reviews[i].url;

      $.ajax({
        url: '/users/:id/bins',
        method: 'POST',
        data: {
          title: reviews[i].album,
          artist: review[i].artist,
          rating: reviews[i].rating,
          year_released: reviews[i].year,
          date_reviewed: reviews[i].date,
          cover_art: review[i].cover
          }
        })
      }
    });
  };```

Just need to double check that I'm not being lost.

Thanks

**Comment by WilliamfShaw** [comment]
@bigtone1284 Im on it.
