### ISSUE TITLE
multiple copies of the same object returned from search

### ISSUE THREAD

**Issue by wbarbee** [wbarbee/bin_app#19]
@bigtone1284  @WilliamfShaw @harimohanraj89 

my search function is returning the information that i want, but it is returning multiple copies of this data. i've tried refactoring the function, to no avail. the objects are then being past to another view where i intend to render this data to the el and i'm encountering an error with my post route. 

```  search: function() {
    console.log('search button clicked');
    var albumQuery = $('#search-input').val();
    var view = this;

    $.ajax({
      url: '/albums?albums=' + albumQuery,
      method: 'GET'
    })
    .done(function(reviews) {
      App.albumsView.renderAll(reviews);

    })
    .fail(function() {
      console.log('You  fail, you fucking fuck.');
    });

  },```

No rush, but would appreciate any assistance. 

Thank you.

**Comment by bigtone1284** [comment]
taken.
