### ISSUE TITLE
only one album showing

### ISSUE THREAD

**Issue by wbarbee** [wbarbee/bin_app#27]
@DrRobotmck @WilliamfShaw @harimohanraj89 

i have all of the data showing for a given artist in the right format with an album cover, but it has been whittled down to one album result throughout a horrible journey that i took over the past couple of hours. If an artist has our albums, only the album at index 1 shows.

Additionally, if that artist only has one album in Pitchfork's database [0], it will not be sent to the  browser at all...

```  renderAllRecent: function(recentAlbums) {
      $('#albums').show();
      console.log(recentAlbums);
      var view = this;

        $.ajax({
          url: '/albums',
          method: 'GET'
        }).done(function(recentAlbums) {
          console.log(recentAlbums);
          for(var i = 0; i < recentAlbums.length; i++) {
            var query = recentAlbums[i];
          $.post('/albums/album_saves', {
              artist: query.artist,
              cover_art: query.cover,
              date_reviewed: query.date,
              rating: query.rating,
              review_url: 'http://www.pitchfork.com' + query.url,
              title: query.album,
              year_released: query.year
          }).done(function(recentData) {
            view.renderOneRecent(recentData);
          });
        }
      });
    },

    renderOneRecent: function(recentData) {
      var previewTemplate = Handlebars.compile($('#preview-template').html());
      var singleAlbum = new App.Views.SingleAlbumView();
      this.$el.append(previewTemplate(recentData));
      for(var i = 0; i < recentData.length; i++) {
        $('#inner-album').append(App.Views.AlbumsView.$el);
      }
    },```

**Comment by WilliamfShaw** [comment]
@wbarbee what have you tried so far?

**Comment by wbarbee** [comment]
@WilliamfShaw i was getting all of these errors from a forEach function that wasn't valid, so i switched it to a reg for loop, which allowed me to actually see something.  then, i started getting a sequelize error pointing to the 'map' of the following function, which is the central route of my entire "app":

```albumRouter.get('/', function(req, res) {
  console.log(req.query.albums);
  var search = new p4k.Search(req.query.albums);
  search.promise.then(function(results){
    // returns the JSON-friendly review
    var reviews = results.map(function(rev){ return rev.attributes; })
    // send back an array of reviews that match the search. may want to do some filtering here?
    res.send(reviews);
  });
});```

**Comment by WilliamfShaw** [comment]
@wbarbee what does the error of the map say?

**Comment by wbarbee** [comment]
cannot read property of 'map' undefined. the first result goes through for some reason

**Comment by WilliamfShaw** [comment]
have you checked what the result of the map is?

**Comment by wbarbee** [comment]
questioning whether i should even be using a 'POST' where i currently am, if i'm just trying to see post results

**Comment by wbarbee** [comment]
fixed it. i know you guys are beat, but thanks for all  of your help, really.

**Comment by WilliamfShaw** [comment]
Nice man!! Glad you fixed it!!
